# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b2523891a50252879f53f20771c4455c0082bcc8c8261e3991ae0e4f78f8696de4d5ddf7f415c62d55ceb2df2fe1a39901f1afeae145e7f29d8ad3e58e0a2d9

test:
  secret_key_base: 0fde416647d0535c4dd664927a64910604daeed11ef052367fcf6516d9bcfa182fbe1303fc461427034eef81b389d8afbf2b02dcd9afee99f254b0601c318e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
